/**
 * Curated Realistic French Business Prospects Dataset
 * Covers Paris, Lyon, Bordeaux, Marseille, Nantes
 * Includes categories: Restaurant, Salon/Coiffure, Artisan/BTP, Avocat, Salle de sport
 */

export const INITIAL_PROSPECTS = [
  {
    id: 'lead-1',
    name: 'Bistrot Saint-Germain',
    category: 'Restaurant & Brasserie',
    city: 'Paris',
    address: '42 Rue Bonaparte, 75006 Paris',
    lat: 48.8534,
    lng: 2.3332,
    hasEmail: true,
    email: 'contact@bistrotsaintgermain-paris.fr',
    phone: '+33 1 43 26 12 34',
    website: 'http://bistrotsaintgermain-paris.fr',
    instagram: '@bistrotsaintgermain',
    facebook: 'BistrotSaintGermainOfficial',
    rating: 4.2,
    reviewsCount: 184,
    auditScore: 48,
    mobileScore: 38,
    seoScore: 52,
    accessScore: 45,
    speedScore: 40,
    painPoints: [
      'Site non sécurisé (HTTP sans certificat SSL)',
      'Aucun menu consultable sur smartphone (PDF lourd non adapté)',
      'Absence de système de réservation en ligne (TheFork ou direct)',
      'Temps de chargement mobile critique : 5.8 secondes'
    ],
    redesignAngle: 'Réservation en 1 clic + Menu interactif QR Code & Mobile First',
    status: 'nouveau', // nouveau, qualifie, proposition_envoyee, discussion, gagne, perdu
    lastContact: 'Non contacté',
    nextFollowup: 'À planifier',
    notes: 'Emplacement premium, fort potentiel si réservation en ligne ajoutée.'
  },
  {
    id: 'lead-2',
    name: 'Atelier Coiffure & Barbier L\'Élégant',
    category: 'Salon de Coiffure',
    city: 'Lyon',
    address: '14 Rue Mercière, 69002 Lyon',
    lat: 45.7628,
    lng: 4.8329,
    hasEmail: false, // Jaune : contact par DM !
    email: '',
    phone: '+33 4 78 37 99 10',
    website: '', // Pas de site web !
    instagram: '@lelegant_barber_lyon',
    facebook: 'LElegantBarbierLyon',
    rating: 4.8,
    reviewsCount: 312,
    auditScore: 25,
    mobileScore: 0,
    seoScore: 30,
    accessScore: 20,
    speedScore: 0,
    painPoints: [
      'Aucun site web officiel : dépendance totale à Instagram',
      'Perte de tous les clients cherchant "barbier lyon 2" sur Google',
      'Réservations gérées manuellement en DM (perte de temps)',
      'Manque de visibilité sur les tarifs et prestations'
    ],
    redesignAngle: 'Création site vitrine ultra-sombre & module Planity / Calendly intégré',
    status: 'qualifie',
    lastContact: 'Hier (Audit généré)',
    nextFollowup: 'Dans 2 jours',
    notes: 'Excellents avis Google, ont un besoin urgent de site vitrine pour professionnaliser.'
  },
  {
    id: 'lead-3',
    name: 'Cabinet Rénovation & Électricité Aquitaine',
    category: 'Artisan & Bâtiment',
    city: 'Bordeaux',
    address: '88 Cours Victor Hugo, 33000 Bordeaux',
    lat: 44.8351,
    lng: -0.5724,
    hasEmail: true,
    email: 'devis@renov-aquitaine-btp.com',
    phone: '+33 5 56 44 88 22',
    website: 'https://renovation-aquitaine.wixsite.com/site',
    instagram: '',
    facebook: 'RenovationAquitaineBordeaux',
    rating: 3.9,
    reviewsCount: 47,
    auditScore: 54,
    mobileScore: 45,
    seoScore: 58,
    accessScore: 60,
    speedScore: 52,
    painPoints: [
      'Sous-domaine Wix gratuit décrédibilisant pour des devis à >10 000€',
      'Formulaire de devis cassé sur smartphone (bouton hors écran)',
      'Absence de galerie photos des réalisations avant/après',
      'Aucune preuve sociale ni avis clients mis en avant'
    ],
    redesignAngle: 'Refonte crédibilité BTP + Calculateur de devis instantané haute conversion',
    status: 'proposition_envoyee',
    lastContact: 'Il y a 3 jours',
    nextFollowup: 'Aujourd\'hui (Relance J+3)',
    notes: 'Proposition envoyée angle ROI Chiffre d\'Affaires. Email ouvert 2 fois.'
  },
  {
    id: 'lead-4',
    name: 'Maître Valérie Martin — Avocat Droit des Affaires',
    category: 'Cabinet d\'Avocats',
    city: 'Marseille',
    address: '25 Rue Paradis, 13001 Marseille',
    lat: 43.2941,
    lng: 5.3768,
    hasEmail: true,
    email: 'contact@martin-avocat-marseille.fr',
    phone: '+33 4 91 13 45 67',
    website: 'http://valerie-martin-avocats.fr',
    instagram: '',
    facebook: '',
    rating: 4.6,
    reviewsCount: 38,
    auditScore: 42,
    mobileScore: 35,
    seoScore: 48,
    accessScore: 40,
    speedScore: 45,
    painPoints: [
      'Design daté des années 2012 (tableaux HTML, non responsive)',
      'Aucune prise de rendez-vous en ligne pour les consultations',
      'Texte illisible sur smartphone sans zoomer',
      'Non-conformité RGPD (absence de bandeau cookies et mentions claires)'
    ],
    redesignAngle: 'Refonte sobre, prestigieuse & prise de RDV consultation payante',
    status: 'discussion',
    lastContact: 'Hier 16:30',
    nextFollowup: 'Vendredi 10h (Appel visio)',
    notes: 'Avocate très intéressée par la modernisation de son image.'
  },
  {
    id: 'lead-5',
    name: 'Iron Cross Training & Fitness Club',
    category: 'Salle de sport',
    city: 'Nantes',
    address: '12 Rue de Strasbourg, 44000 Nantes',
    lat: 47.2184,
    lng: -1.5536,
    hasEmail: false,
    email: '',
    phone: '+33 2 40 89 77 11',
    website: 'http://ironcross-nantes.fr',
    instagram: '@ironcross_nantes',
    facebook: 'IronCrossNantes',
    rating: 4.7,
    reviewsCount: 220,
    auditScore: 58,
    mobileScore: 50,
    seoScore: 65,
    accessScore: 55,
    speedScore: 62,
    painPoints: [
      'Bouton "Essai gratuit" redirigeant vers une page 404',
      'Planning des cours non synchronisé et non lisible sur mobile',
      'Pas de vidéo ni de visite virtuelle de la salle',
      'Temps de chargement ralenti par des images de 12 Mo non compressées'
    ],
    redesignAngle: 'Landing page ultra-dynamique, vidéo hero + Inscription séance d\'essai offerte',
    status: 'nouveau',
    lastContact: 'Non contacté',
    nextFollowup: 'À planifier',
    notes: 'Excellente communauté Instagram, prospect idéal pour DM avec mockup vidéo.'
  },
  {
    id: 'lead-6',
    name: 'Boulangerie Pâtisserie Maison Delmas',
    category: 'Artisan & Alimentation',
    city: 'Paris',
    address: '18 Rue des Martyrs, 75009 Paris',
    lat: 48.8789,
    lng: 2.3398,
    hasEmail: true,
    email: 'bonjour@maisondelmas-paris.fr',
    phone: '+33 1 48 78 50 12',
    website: 'http://delmas-patisserie.fr',
    instagram: '@maisondelmas_paris',
    facebook: 'MaisonDelmasParis',
    rating: 4.9,
    reviewsCount: 520,
    auditScore: 36,
    mobileScore: 30,
    seoScore: 40,
    accessScore: 35,
    speedScore: 40,
    painPoints: [
      'Site en maintenance depuis 6 mois avec simple page blanche',
      'Aucun catalogue traiteur / gâteaux d\'anniversaire en ligne',
      'Clients obligés d\'appeler ou passer sur place pour commander',
      'Perte d\'un chiffre d\'affaires traiteur estimé à 2 500€/mois'
    ],
    redesignAngle: 'Boutique Click & Collect + Catalogue gâteaux sur-mesure',
    status: 'gagne',
    lastContact: 'Signé ce matin',
    nextFollowup: 'Livraison vendredi',
    notes: 'Devis signé à 1 800€ + abonnement maintenance 90€/mois.'
  }
];
